import subprocess
import time

subprocess.call("irsend SEND_ONCE LED_24_KEY BLUE", shell=True)
time.sleep(1)
subprocess.call("irsend SEND_ONCE LED_24_KEY RED", shell=True)
time.sleep(1)
subprocess.call("irsend SEND_ONCE LED_24_KEY GREEN", shell=True)
time.sleep(0.5)
subprocess.call("irsend SEND_ONCE LED_24_KEY 7_FADE", shell=True)
time.sleep(0.3)
subprocess.call("irsend SEND_ONCE LED_24_KEY BLUE", shell=True)
time.sleep(1.5)
subprocess.call("irsend SEND_ONCE LED_24_KEY ALL_FADE", shell=True)
time.sleep(1)
subprocess.call("irsend SEND_ONCE LED_24_KEY RED", shell=True)
time.sleep(0.1)
subprocess.call("irsend SEND_ONCE LED_24_KEY GREEN", shell=True)
time.sleep(0.1)
subprocess.call("irsend SEND_ONCE LED_24_KEY BLUE", shell=True)
time.sleep(0.1)
subprocess.call("irsend SEND_ONCE LED_24_KEY RED", shell=True)
time.sleep(0.1)
subprocess.call("irsend SEND_ONCE LED_24_KEY GREEN", shell=True)
time.sleep(0.1)
subprocess.call("irsend SEND_ONCE LED_24_KEY BLUE", shell=True)
time.sleep(0.1)
subprocess.call("irsend SEND_ONCE LED_24_KEY RED", shell=True)
time.sleep(0.1)
subprocess.call("irsend SEND_ONCE LED_24_KEY GREEN", shell=True)
time.sleep(0.1)
subprocess.call("irsend SEND_ONCE LED_24_KEY BLUE", shell=True)
time.sleep(0.1)
subprocess.call("irsend SEND_ONCE LED_24_KEY RED", shell=True)
time.sleep(0.1)
subprocess.call("irsend SEND_ONCE LED_24_KEY GREEN", shell=True)
time.sleep(0.1)
subprocess.call("irsend SEND_ONCE LED_24_KEY BLUE", shell=True)
time.sleep(0.1)
subprocess.call("irsend SEND_ONCE LED_24_KEY RED", shell=True)
time.sleep(0.1)
subprocess.call("irsend SEND_ONCE LED_24_KEY GREEN", shell=True)
time.sleep(0.1)
subprocess.call("irsend SEND_ONCE LED_24_KEY BLUE", shell=True)
time.sleep(0.1)
subprocess.call("irsend SEND_ONCE LED_24_KEY RED", shell=True)
time.sleep(0.1)
subprocess.call("irsend SEND_ONCE LED_24_KEY GREEN", shell=True)
time.sleep(0.1)
subprocess.call("irsend SEND_ONCE LED_24_KEY BLUE", shell=True)
time.sleep(0.1)
subprocess.call("irsend SEND_ONCE LED_24_KEY RED", shell=True)
time.sleep(0.1)
subprocess.call("irsend SEND_ONCE LED_24_KEY GREEN", shell=True)
time.sleep(0.1)
subprocess.call("irsend SEND_ONCE LED_24_KEY BLUE", shell=True)
time.sleep(0.1)
subprocess.call("irsend SEND_ONCE LED_24_KEY RED", shell=True)
time.sleep(0.1)
subprocess.call("irsend SEND_ONCE LED_24_KEY GREEN", shell=True)
time.sleep(0.1)
subprocess.call("irsend SEND_ONCE LED_24_KEY BLUE", shell=True)
time.sleep(0.1)
subprocess.call("irsend SEND_ONCE LED_24_KEY RED", shell=True)
time.sleep(0.1)
subprocess.call("irsend SEND_ONCE LED_24_KEY GREEN", shell=True)
time.sleep(0.1)
subprocess.call("irsend SEND_ONCE LED_24_KEY BLUE", shell=True)
time.sleep(0.1)